### ISSUE TITLE
gatsby-plugin-feed title validation Error

### ISSUE THREAD

**Issue by mskian** [TryGhost/gatsby-starter-ghost#78] opened 2019-08-26 04:57 UTC
Today I update the Gatsby Plugin Feed plugin from `2.3.6` to `2.3.9`
I found this Bug while Building the Gatsby Site

```js
$ gatsby build

success open and validate gatsby-configs - 0.127 s
success load plugins - 0.693 s
success onPreInit - 0.017 s
success delete html and css files from previous builds - 0.027 s
success initialize cache - 0.021 s
success copy gatsby files - 0.043 s

 ERROR #11321  PLUGIN

"gatsby-plugin-feed" threw an error while running the onPreBootstrap lifecycle:

[Config Validation]: "title" is required



  Error: [Config Validation]: "title" is required
  
  - gatsby-node.js:84 _callee$
    [gatsby-starter-ghost]/[gatsby-plugin-feed]/gatsby-node.js:84:19
  

⠋ onPreBootstrap
```

rollback the Feed Plugin to ` 2.3.6` it working well

**Comment by AileenCGN** [comment] 2019-08-27 07:59
This is tracked here: https://github.com/gatsbyjs/gatsby/issues/17100

Closing this issue, as it's not a bug within this starter.

**Closed by AileenCGN** 2019-08-27 07:59 UTC
