### ISSUE TITLE
Javascript widgets in posts not working

### ISSUE THREAD

**Issue by styxlab** [TryGhost/gatsby-starter-ghost#105] opened 2020-02-19 19:11 UTC
### Issue Summary

Javascript widgets in posts are not rendered correctly. For example, look at the Zappier Widget in the original [Ghost Demo](https://demo.ghost.io/apps-integrations/) versus the [Gatsby-Ghost Demo](https://gatsby.ghost.org/apps-integrations/) where the widget is *not* shown below the line "Here are the most popular Ghost<>Zapier automation templates:".

### Technical details

This repo already has a [mechanism](https://github.com/TryGhost/gatsby-starter-ghost/blob/master/gatsby-browser.js) to incorporate scripts that are embedded in posts. I'm not sure if the problem is technically similar to #22, but it is a different use case.

### Expectation

Embedded javascript code in posts should work when sourcing content from the Ghost CMS. When using Ghost as a headless CMS it is important that posts containing widgets are rendered without tweaking the gatsby source code.

**Comment by AileenCGN** [comment] 2020-03-02 03:54
Hmm... I can't reproduce this. The embed is showing fine for me on https://gatsby.ghost.org/apps-integrations/:

<img width="944" alt="image" src="https://user-images.githubusercontent.com/8037602/75644220-80832580-5c7c-11ea-8650-ad7d6847efa4.png">

Going to close this issue. Please let me know if you think this is still an issue, we can always reopen it.

**Closed by AileenCGN** 2020-03-02 03:54 UTC

**Comment by styxlab** [comment] 2020-03-02 10:23
Kind of funny that it does works when going directly to https://gatsby.ghost.org/apps-integrations/ with the Firefox browser. I tested with recent versions of the following browsers:

- Firefox (desktop + mobile): working
- Safari (mobile): not working
- Edge (desktop): not working
- Chrome (desktop): not working

Also, it is **not working** even with Firefox, when you first go to https://gatsby.ghost.org and subsequently click on the "Apps & integrations" post.

Chrome shows the following error in the console: *Uncought TypeError: Cannot read property addEventListener' of null (widget.js: 557)*. Maybe this helps in finding the root cause of this issue.

Please re-open the issue as it is not solved.
