### ISSUE TITLE
Can't resolve 'core-js/modules/es.array.flat' and 'core-js/modules/es.array.unscopables.flat'

### ISSUE THREAD

**Issue by standingdreams** [TryGhost/gatsby-starter-ghost#226] opened 2020-07-14 21:57 UTC
### Issue Summary
The most recent dependency update is causing errors with core-js. I've attempted to download and install previous commits with no issue. Only the most recent is breaking. I've tried downloading from Github and installing by `gatsby new`. It seems like this has been an issue [previously](https://github.com/gatsbyjs/gatsby/issues/7862). I've tried installing core-js and still have the same issue.

### Technical details:
Ghost-CLI version: 1.14.1
Gatsby CLI version: 2.12.60
Gatsby version: 2.23.20
Node Version: v12.17.0
OS: Mac OS X 10.15.5

**Comment by oliviachang29** [comment] 2020-07-18 20:03
Same, getting this error on a fresh install.

**Comment by deepinder10** [comment] 2020-07-18 21:54
+1

**Comment by phillipzink** [comment] 2020-07-19 00:46
Same problem here:
https://github.com/TryGhost/gatsby-starter-ghost/issues/226

I ran this to upgrade gatsby.
npm install gatsby@2.24.4 --save

**Comment by JustFly1984** [comment] 2020-08-05 07:38
receiving this error in one of my projects with gatsby@2.23.22

**Comment by daniellockyer** [comment] 2020-08-13 08:37
Hey everyone :wave: I tried to reproduce this locally but I don't seem to be able to.

Would someone be able to give reproduction steps to produce the error?

**Comment by aileen** [comment] 2020-09-15 02:23
I'm not able to reproduce and it seems to be an upstream issue. Closing this for now. We can always re-open if it's clearly a bug 😃

**Closed by aileen** 2020-09-15 02:23 UTC

**Comment by LukeXF** [comment] 2020-10-12 16:48
I also have this issue, did anyone get to the bottom of this? 

```
Can't resolve 'core-js/modules/es.array.flat'
If you're trying to use a package make sure that 'core-js/modules/es.array.flat' is installed. If you're trying to use a local file make sure that the path is correct.
error Generating JavaScript bundles failed
Can't resolve 'core-js/modules/es.array.unscopables.flat' 
```

**Comment by wardpeet** [comment] 2020-10-12 20:39
@LukeXF mind sharing a repro?

**Comment by LukeXF** [comment] 2020-10-20 11:10
> @LukeXF mind sharing a repro?

It's a private repos so I wouldn't be able to. But we resolved this issue by deleting node modules and yarn.lock and then doing a fresh install. Still not sure what caused this.

**Comment by JustFly1984** [comment] 2020-10-21 03:33
@LukeXF  I had to update to latest version and remove yarn.lock and reinstall all packages with Node 14 enabled in nvm to resolve this issue last week.
