### ISSUE TITLE
Errors on first run

### ISSUE THREAD

**Issue by eblohm** [TryGhost/gatsby-starter-ghost#84] opened 2019-10-15 23:33 UTC
Trying to get this up and running and after I install it with the command

`gatsby new project-name https://github.com/TryGhost/gatsby-starter-ghost.git`

And run gatsby develop, I get the following error. A regular Gatsby install works fine, for what it's worth.

```javascript
ERROR 

The above error occurred in the <ReduxStoreProvider> component:
    in ReduxStoreProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.


 ERROR 

Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.


 ERROR 

UNHANDLED REJECTION Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.



  Error: Invariant Violation: Invalid hook call. Hooks can only be called inside   of the body of a function component. This could happen for one of the followi  ng reasons:
  1. You might have mismatching versions of React and the renderer (such as Reac  t DOM)
  2. You might be breaking the Rules of Hooks
  3. You might have more than one copy of React in the same app
  See https://fb.me/react-invalid-hook-call for tips about how to debug and fix   this problem.
  
  - react.development.js:1607 
    [project-name]/[gatsby]/[react]/cjs/react.development.js:1607:26
  
  - react.development.js:1610 resolveDispatcher
    [project-name]/[gatsby]/[react]/cjs/react.development.js:1610:5
  
  - react.development.js:1636 useState
    [project-name]/[gatsby]/[react]/cjs/react.development.js:1636:20
  
  - index.js:28 ReduxStoreProvider
    [project-name]/[gatsby]/[gatsby-cli]/lib/reporter/loggers/ink/index.js:28:41
  
  - react-reconciler.development.js:5671 renderWithHooks
    [project-name]/[react-reconciler]/cjs/react-reconciler.development.js:5671:18
  
  - react-reconciler.development.js:7905 mountIndeterminateComponent
    [project-name]/[react-reconciler]/cjs/react-reconciler.development.js:7905:13
  
  - react-reconciler.development.js:9049 beginWork$1
    [project-name]/[react-reconciler]/cjs/react-reconciler.development.js:9049:16
  
  - react-reconciler.development.js:10317 Object.invokeGuardedCallbackImpl
    [project-name]/[react-reconciler]/cjs/react-reconciler.development.js:10317:10
  
  - react-reconciler.development.js:10501 invokeGuardedCallback
    [project-name]/[react-reconciler]/cjs/react-reconciler.development.js:10501:31
  
  - react-reconciler.development.js:14014 beginWork$$1
    [project-name]/[react-reconciler]/cjs/react-reconciler.development.js:14014:7
```

### Technical details:

* Ghost Version: 1.11.0
* Gatsby Version: 2.15.18
* Gatsby-CLI Version: 2.8.1
* Node Version: 10.16.3
* OS: Ubuntu 18.04

The machine is a relatively fresh install of Ubuntu, there's little installed other than Node and NPM. I've also tried it on a Windows 10 machine with the same Node, Ghost, Gatsby & Gatsby-CLI version.

**Comment by mskian** [comment] 2019-10-17 03:56
```bash
git clone https://github.com/TryGhost/gatsby-starter-ghost.git
cd gatsby-starter-ghost
yarn
yarn dev
```

**Comment by AileenCGN** [comment] 2019-10-23 05:46
@eblohm I am not able to reproduce your issue. What are the exact steps that you took?

Your Ghost version (1.11.0)  is also not supported, as mentioned in the README.

I'm going to close this issue, but please let me know if you keep having trouble and if it turns out to be a bug, we can always reopen it.

**Closed by AileenCGN** 2019-10-23 05:46 UTC
