### ISSUE TITLE
Netlify deploy error

### ISSUE THREAD

**Issue by denistravis** [TryGhost/gatsby-starter-ghost#231] opened 2020-07-22 11:22 UTC
Getting this error while deploying to netlify

`1:40:35 PM: Build ready to start
1:40:36 PM: build-image version: ca811f47d4c1cbd1812d1eb6ecb0c977e86d1a1d
1:40:36 PM: build-image tag: v3.3.20
1:40:36 PM: buildbot version: be8ecf2af866e16fa4301cc5c14de2ccbbb21cf4
1:40:37 PM: Fetching cached dependencies
1:40:37 PM: Failed to fetch cache, continuing with build
1:40:37 PM: Starting to prepare the repo for build
1:40:37 PM: No cached dependencies found. Cloning fresh repo
1:40:37 PM: git clone https://github.com/TryGhost/gatsby-starter-ghost
1:40:39 PM: Preparing Git Reference refs/heads/master
1:40:40 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'public' versus 'public/' in the Netlify UI
1:40:40 PM: Starting build script
1:40:40 PM: Installing dependencies
1:40:40 PM: Python version set to 2.7
1:40:40 PM: Attempting node version '12' from .nvmrc
1:40:41 PM: Downloading and installing node v12.18.2...
1:40:41 PM: Downloading https://nodejs.org/dist/v12.18.2/node-v12.18.2-linux-x64.tar.xz...
1:40:41 PM: Computing checksum with sha256sum
1:40:42 PM: Checksums matched!
1:40:44 PM: Now using node v12.18.2 (npm v6.14.5)
1:40:44 PM: Started restoring cached build plugins
1:40:44 PM: Finished restoring cached build plugins
1:40:44 PM: Attempting ruby version 2.7.1, read from environment
1:40:46 PM: Using ruby version 2.7.1
1:40:46 PM: Using PHP version 5.6
1:40:46 PM: 5.2 is already installed.
1:40:46 PM: Using Swift version 5.2
1:40:46 PM: Started restoring cached node modules
1:40:46 PM: Finished restoring cached node modules
1:40:46 PM: Started restoring cached yarn cache
1:40:46 PM: Finished restoring cached yarn cache
1:40:46 PM: Installing yarn at version 1.22.4
1:40:46 PM: Installing Yarn!
1:40:46 PM: > Downloading tarball...
1:40:46 PM: [1/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz --> /tmp/yarn.tar.gz.nfang1RzaQ
1:40:46 PM:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
1:40:46 PM:                                  Dload  Upload   Total   Spent    Left  Speed
1:40:46 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
1:40:46 PM: 100    80  100    80    0     0    257      0 --:--:-- --:--:-- --:--:--   258
1:40:47 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
1:40:47 PM: 100    93  100    93    0     0    145      0 --:--:-- --:--:-- --:--:--  1430
1:40:47 PM: 100   630  100   630    0     0    696      0 --:--:-- --:--:-- --:--:--   696
1:40:47 PM: 100 1215k  100 1215k    0     0   907k      0  0:00:01  0:00:01 --:--:--  907k
1:40:47 PM: [2/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz.asc --> /tmp/yarn.tar.gz.nfang1RzaQ.asc
1:40:47 PM: 100    84  100    84    0     0   3049      0 --:--:-- --:--:-- --:--:--  3049
1:40:47 PM: 100    97  100    97    0     0   1712      0 --:--:-- --:--:-- --:--:--  1712
1:40:47 PM: 100   634  100   634    0     0   7163      0 --:--:-- --:--:-- --:--:--  7163
1:40:48 PM: 100  1028  100  1028    0     0   7835      0 --:--:-- --:--:-- --:--:--  7835
1:40:48 PM: > Verifying integrity...
1:40:48 PM: gpg: Signature made Mon 09 Mar 2020 03:52:13 PM UTC using RSA key ID 69475BAA
1:40:48 PM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
1:40:48 PM: gpg: WARNING: This key is not certified with a trusted signature!
1:40:48 PM: gpg:          There is no indication that the signature belongs to the owner.
1:40:48 PM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
1:40:48 PM:      Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
1:40:48 PM: > GPG signature looks good
1:40:48 PM: > Extracting to ~/.yarn...
1:40:48 PM: > Adding to $PATH...
1:40:48 PM: > Successfully installed Yarn 1.22.4! Please open another terminal where the `yarn` command will now be available.
1:40:48 PM: Installing NPM modules using Yarn version 1.22.4
1:40:49 PM: yarn install v1.22.4
1:40:49 PM: [1/5] Validating package.json...
1:40:49 PM: [2/5] Resolving packages...
1:40:50 PM: [3/5] Fetching packages...
1:40:56 PM: warning url-loader@1.1.2: Invalid bin field for "url-loader".
1:41:18 PM: info fsevents@2.1.3: The platform "linux" is incompatible with this module.
1:41:18 PM: info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
1:41:18 PM: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
1:41:18 PM: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
1:41:18 PM: [4/5] Linking dependencies...
1:41:18 PM: warning "gatsby > @pmmmwh/react-refresh-webpack-plugin@0.3.3" has incorrect peer dependency "react-refresh@^0.8.2".
1:41:18 PM: warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
1:41:35 PM: [5/5] Building fresh packages...
1:41:40 PM: Done in 51.04s.
1:41:40 PM: NPM modules installed using Yarn
1:41:40 PM: Started restoring cached go cache
1:41:40 PM: Finished restoring cached go cache
1:41:40 PM: go version go1.14.4 linux/amd64
1:41:40 PM: go version go1.14.4 linux/amd64
1:41:40 PM: Installing missing commands
1:41:40 PM: Verify run directory
1:41:42 PM: ​
1:41:42 PM: ┌─────────────────────────────┐
1:41:42 PM: │        Netlify Build        │
1:41:42 PM: └─────────────────────────────┘
1:41:42 PM: ​
1:41:42 PM: ❯ Version
1:41:42 PM:   @netlify/build 3.0.1
1:41:42 PM: ​
1:41:42 PM: ❯ Flags
1:41:42 PM:   deployId: 5f1817a238ffe28491742587
1:41:42 PM:   mode: buildbot
1:41:42 PM: ​
1:41:42 PM: ❯ Current directory
1:41:42 PM:   /opt/build/repo
1:41:42 PM: ​
1:41:42 PM: ❯ Config file
1:41:42 PM:   /opt/build/repo/netlify.toml
1:41:42 PM: ​
1:41:42 PM: ❯ Context
1:41:42 PM:   production
1:41:42 PM: ​
1:41:42 PM: ┌────────────────────────────────────┐
1:41:42 PM: │ 1. build.command from netlify.toml │
1:41:42 PM: └────────────────────────────────────┘
1:41:42 PM: ​
1:41:42 PM: $ NODE_ENV=production gatsby build
1:41:45 PM: error We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.
1:41:45 PM: 
1:41:45 PM:   Error: siteUrl can't be localhost and needs to be configured in siteConfig. Ch  eck the README.  
1:41:45 PM:   - gatsby-config.js:26 Object.<anonymous>
1:41:45 PM:     /opt/build/repo/gatsby-config.js:26:11
1:41:45 PM:   
1:41:45 PM:   - v8-compile-cache.js:178 Module._compile
1:41:45 PM:     [repo]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:178:30
1:41:45 PM:   
1:41:45 PM:   - loader.js:1158 Object.Module._extensions..js
1:41:45 PM:     internal/modules/cjs/loader.js:1158:10
1:41:45 PM:   
1:41:45 PM:   - loader.js:986 Module.load
1:41:45 PM:     internal/modules/cjs/loader.js:986:32
1:41:45 PM:   
1:41:45 PM:   - loader.js:879 Function.Module._load
1:41:45 PM:     internal/modules/cjs/loader.js:879:14
1:41:45 PM:   
1:41:45 PM:   - loader.js:1026 Module.require
1:41:45 PM:     internal/modules/cjs/loader.js:1026:19
1:41:45 PM:   
1:41:45 PM:   - v8-compile-cache.js:159 require
1:41:45 PM:     [repo]/[gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
1:41:45 PM:   
1:41:45 PM:   - get-config-file.js:33 getConfigFile
1:41:45 PM:     [repo]/[gatsby]/dist/bootstrap/get-config-file.js:33:20
1:41:45 PM:   
1:41:45 PM:   - initialize.js:127 initialize
1:41:45 PM:     [repo]/[gatsby]/dist/services/initialize.js:127:46
1:41:45 PM:   
1:41:45 PM:   - index.js:30 bootstrap
1:41:45 PM:     [repo]/[gatsby]/dist/bootstrap/index.js:30:40
1:41:45 PM:   
1:41:45 PM:   - build.js:96 build
1:41:45 PM:     [repo]/[gatsby]/dist/commands/build.js:96:38
1:41:45 PM:   
1:41:45 PM:   - create-cli.js:226 
1:41:45 PM:     [repo]/[gatsby-cli]/lib/create-cli.js:226:14
1:41:45 PM:   
1:41:45 PM:   - create-cli.js:124 
1:41:45 PM:     [repo]/[gatsby-cli]/lib/create-cli.js:124:24
1:41:45 PM:   
1:41:45 PM:   - create-cli.js:35 Object.handler
1:41:45 PM:     [repo]/[gatsby-cli]/lib/create-cli.js:35:19
1:41:45 PM:   
1:41:45 PM:   - command.js:196 Object.runCommand
1:41:45 PM:     [repo]/[yargs]/build/lib/command.js:196:48
1:41:45 PM:   
1:41:45 PM:   - yargs.js:1043 Object.parseArgs [as _parseArgs]
1:41:45 PM:     [repo]/[yargs]/build/lib/yargs.js:1043:55
1:41:45 PM:   
1:41:45 PM: 
1:41:45 PM: not finished open and validate gatsby-configs - 0.214s
1:41:45 PM: ​
1:41:45 PM: ┌─────────────────────────────┐
1:41:45 PM: │   "build.command" failed    │
1:41:45 PM: └─────────────────────────────┘
1:41:45 PM: ​
1:41:45 PM:   Error message
1:41:45 PM:   Command failed with exit code 1: NODE_ENV=production gatsby build
1:41:45 PM: ​
1:41:45 PM:   Error location
1:41:45 PM:   In build.command from netlify.toml:
1:41:45 PM:   NODE_ENV=production gatsby build
1:41:45 PM: ​
1:41:45 PM:   Resolved config
1:41:45 PM:   build:
1:41:45 PM:     command: NODE_ENV=production gatsby build
1:41:45 PM:     commandOrigin: config
1:41:45 PM:     publish: /opt/build/repo/public
1:41:45 PM: Caching artifacts
1:41:45 PM: Started saving node modules
1:41:45 PM: Finished saving node modules
1:41:45 PM: Started saving build plugins
1:41:45 PM: Finished saving build plugins
1:41:45 PM: Started saving yarn cache
1:41:45 PM: Finished saving yarn cache
1:41:45 PM: Started saving pip cache
1:41:45 PM: Finished saving pip cache
1:41:45 PM: Started saving emacs cask dependencies
1:41:45 PM: Finished saving emacs cask dependencies
1:41:45 PM: Started saving maven dependencies
1:41:45 PM: Finished saving maven dependencies
1:41:45 PM: Started saving boot dependencies
1:41:45 PM: Finished saving boot dependencies
1:41:45 PM: Started saving go dependencies
1:41:45 PM: Finished saving go dependencies
1:41:49 PM: Error running command: Build script returned non-zero exit code: 1
1:41:49 PM: Failing build: Failed to build site
1:41:49 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
1:41:49 PM: Finished processing build request in 1m12.864661781s `

**Comment by hhamud** [comment] 2020-09-07 21:30
Did you solve the problem?

The documentation is not clear on what to change the .ghost.json siteurls to when deploying to netlify as netlify does not recognise localhost domains

**Comment by hhamud** [comment] 2020-09-08 17:24
> Did you solve the problem?
> 
> The documentation is not clear on what to change the .ghost.json siteurls to when deploying to netlify as netlify does not recognise localhost domains

nvm I found way to host ghost locally, you simply need to use ngrok to open up the port where ghost is hosted on (e.g localhost:2368 --> use port 2368), and then copy the address that it gives you to the apiurl in the .ghost.json file

**Comment by aileen** [comment] 2020-09-15 02:22
>  Error: siteUrl can't be localhost and needs to be configured in siteConfig. Ch eck the README.

I think this is pretty clear? Closing as not a bug

**Closed by aileen** 2020-09-15 02:22 UTC
