### ISSUE TITLE
Updating content in ghost cms does not propagate to the gatsby frontend when developing

### ISSUE THREAD

**Issue by matyashlavacek** [TryGhost/gatsby-starter-ghost#120] opened 2020-04-02 15:16 UTC
# Issue Summary

Updating a post in ghost cms does not reflect the change in the gatsby ui when running `gatsby develop`.

### To Reproduce

1. `gatsby new gatsby-starter-ghost https://github.com/TryGhost/gatsby-starter-ghost.git`
2. `cd gatsby-starter-ghost`
3. `docker run -d --name some-ghost -e url=http://localhost:3001 -p 3001:2368 ghost` (This will run ghost cms in a docker container and make it available on localhost:3001
3. create username, log in, create custom integration on  `http://localhost:3001/ghost/`
4. copy pasta `apiUrl` and `contentApiKey` from `http://localhost:3001/ghost/` custom integration to `.ghost.json` under `development` key
5. run `gatsby develop`
6. open browser on `http://localhost:8000/`
7. change a post on `http://localhost:3001/`
8. reload web page on `http://localhost:8000/`
9. change does not get reflected (need to kill `gatsby develop` and run again upon each update)

I expected for the changes in ghost cms to get reflected in the frontend

### Technical details:

* Ghost Version: 3.12.1
* Gatsby Version: 2.19.23
* Node Version: v12.16.1
* OS: macOS Catalina 10.15.3
* Gatsby CLI version: 2.11.4

---
Is this supposed to work or is the manual kill and rerun `gatsby develop` on each iteration the expected workflow?

**Comment by omarkhairy21** [comment] 2020-04-05 23:58
Is this supposed to work or is the manual kill and rerun gatsby develop on each iteration the expected workflow?
yes, as long as the state of your app changes like you fetch data using **staticQuery** this means you need to prerender and querying the data in building time.
So, what is exactly gatsby develop doing?  
> gatsby develop:  Start development server. Watches files, rebuilds, and hot reloads if something changes
 because of gatsby develop just make hot reloads it just watch files if any changes happened like HTML,JSX ,styles..etc
in production, you can automate this process by register webhook by using Ghost custom integrations: Like send an event to netlify to rebuild the website [Netlify + Ghost](https://ghost.org/integrations/netlify/)

**Comment by AileenCGN** [comment] 2020-04-06 00:16
Thanks @omarkhairy21 for the explanation! Closing this, as it's not a bug, but expected behaviour.

**Closed by AileenCGN** 2020-04-06 00:16 UTC
