### ISSUE TITLE
Plugin gatsby-source-ghost returned an error

### ISSUE THREAD

**Issue by slavakurilyak** [TryGhost/gatsby-starter-ghost#44] opened 2019-03-29 04:01 UTC
Running `$ gatsby develop` produces the following error:
```
success open and validate gatsby-configs — 0.116 s
success load plugins — 0.274 s
success onPreInit — 0.789 s
success initialize cache — 0.010 s
success copy gatsby files — 0.095 s
success onPreBootstrap — 0.011 s
error Plugin gatsby-source-ghost returned an error


  Error: Request failed with status code 404

  - createError.js:16 createError
    [blog]/[axios]/lib/core/createError.js:16:15

  - settle.js:18 settle
    [blog]/[axios]/lib/core/settle.js:18:12

  - http.js:201 IncomingMessage.handleStreamEnd
    [blog]/[axios]/lib/adapters/http.js:201:11

  - next_tick.js:63 process._tickCallback
    internal/process/next_tick.js:63:19


success source and transform nodes — 0.674 s
success building schema — 0.404 s
success createPages — 0.059 s
success createPagesStatefully — 0.039 s
success onPreExtractQueries — 0.005 s
success update schema — 0.222 s
warning The GraphQL query in the non-page component "/Users/skurilyak/dev/slavakurilyak/blog/src/templates/author.js" will not be run.
warning The GraphQL query in the non-page component "/Users/skurilyak/dev/slavakurilyak/blog/src/templates/page.js" will not be run.
warning The GraphQL query in the non-page component "/Users/skurilyak/dev/slavakurilyak/blog/src/templates/index.js" will not be run.
warning The GraphQL query in the non-page component "/Users/skurilyak/dev/slavakurilyak/blog/src/templates/post.js" will not be run.
warning The GraphQL query in the non-page component "/Users/skurilyak/dev/slavakurilyak/blog/src/templates/tag.js" will not be run.
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — http://graphql.org/learn/queries/#fragments
success extract queries from components — 0.159 s
success run graphql queries — 0.154 s — 8/8 52.07 queries/second
Generating image thumbnails [==============================] 4/4 0.0 secs 100%
success write out page data — 0.007 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.002 s

info bootstrap finished - 6.54 s

 DONE  Compiled successfully in 2523ms                                                                                                                                                            8:56:22 PM


You can now view gatsby-starter-ghost in the browser.

  http://localhost:8000/

View GraphiQL, an in-browser IDE, to explore your site's data and schema

  http://localhost:8000/___graphql

Note that the development build is not optimized.
To create a production build, use npm run build

ℹ ｢wdm｣:
ℹ ｢wdm｣: Compiled successfully.
```

Steps to Re-Create Issue:
1. `$ sudo mkdir -p ghost`
2. `$ sudo chown -R $(whoami) ghost`
3. `$ sudo chmod 775 ghost`
4. `$ cd ghost`
5. `$ ghost install local`
6. `$ cd ..`
7. `$ gatsby new blog https://github.com/TryGhost/gatsby-starter-ghost.git`
8. `$ cd blog`
9. `$ yarn`
10. `$ gatsby develop`

Please advise. Thanks in advance.

**Comment by AileenCGN** [comment] 2019-03-29 04:23
From the README: 

> To use your own install, edit the `.ghost.json` config file with your credentials. You can find your `contentApiKey` in the "Integrations" screen in Ghost Admin.

What does your `.ghost.json` file look like?

Are you running Ghost locally for development purposes? Which OS are you running it on? If you're planning to use it for production, you should install it as such (without `local`) and have it running on a URL accessible from the outside.

Sounds also very much like this here: https://forum.ghost.org/t/no-ghost-in-gatsby-ghost-starter/6251 and this here: https://forum.ghost.org/t/access-admin-panel-with-gatsby-plugin/5694

Closing this, as it's not a bug 😄

**Closed by AileenCGN** 2019-03-29 04:23 UTC

**Comment by slavakurilyak** [comment] 2019-03-31 04:00
@AileenCGN please update README to include information about deploying Gatsby and Ghost separately.
