### ISSUE TITLE
Gallery Renders Images Differently on Ghost Site Preview and Gatsby Build

### ISSUE THREAD

**Issue by noce2** [TryGhost/gatsby-starter-ghost#280] opened 2020-10-17 12:23 UTC
Hi, please could I have some help with this issue I'm seeing?

### Issue Summary

A gallery widget that renders properly in a local ghost site preview does not render correctly in the gatsby generated version of the site.

On Ghost Site Preview: 
![image](https://user-images.githubusercontent.com/20339399/96336918-c7425600-107a-11eb-918d-8628569d2df3.png)

On Gatsby Generated Site:
![image](https://user-images.githubusercontent.com/20339399/96336968-315afb00-107b-11eb-9eb7-92350733a59b.png)

### To Reproduce

1. Set up a locally running version of ghost and integrate with the Gatsby starter
2. On a post, include a gallery widget with 3 images
3. Build and serve the Gatsby generated site using the `gatsby develop`.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 3.35.5 
* Gatsby Version: 2.24.78 (2.12.109 - CLI)
* Gatsby-Source-Ghost: 4.2.1
* Node Version: 12.18.3
* OS: Windows 10

**Comment by aileen** [comment] 2020-10-18 22:19
Hey @noce2 

This is not a bug, but rather intentional. The Gatsby starter is a "starter" and not meant to be a fully styled theme. It comes with some basic styles to get you started. Comparing it to the Ghost frontend using Casper is not the same, as Casper or any other theme has their own styles to render image galleries.

I'm closing this, as it's not a bug.

**Closed by aileen** 2020-10-18 22:19 UTC
