### ISSUE TITLE
Feature image of posts not included in build

### ISSUE THREAD

**Issue by bst27** [TryGhost/gatsby-starter-ghost#101] opened 2020-01-20 22:08 UTC
### Issue Summary

When building using **npm run build** the feature images of the posts created in Ghost are not included. 

### To Reproduce

1. `git clone https://github.com/TryGhost/gatsby-starter-ghost.git`
2. `cd gatsby-starter-ghost/`
3. `yarn`
4. `docker run --rm -d --name ghostcms-test -p 3001:2368 -v ghostcms-content-test:/var/lib/ghost/content -e url=http://localhost:3001/ ghost`
5. Create custom integration via webinterface: http://localhost:3001/ghost/#/settings/integrations
6. Change feature image of "Welcome to Ghost" post by uploading any image
7. Set URL and key for API in **.ghost.json** (http://localhost:3001 + previously generated integration key)
8. `yarn run build`
9. Access generated static content in *public* directory using any webserver
10. Notice the missing feature image for "Welcome to Ghost" post

Browser console says:
`Network request for 'http://localhost:3001/content/images/2020/01/example-1.jpg' threw an error. TypeError: Failed to fetch`

This also affects images embedded in the post when inserting them using the Ghost editor. Using the graphql explorer (http://localhost:8000/___graphql) you can inspect the posts html code:
`query MyQuery {
  allGhostPost {
    edges {
      node {
        html
      }
    }
  }
}
`

`... <figure class=\"kg-card kg-image-card\"><img src=\"http://localhost:3001/content/images/2020/01/my-embedded-image.jpg\" class=\"kg-image\" alt=\"Example\"></figure> ...`

What do I expect: I expect to have the feature images and embedded images of posts be included during static site generation.

### Technical details:

* Ghost Version: 3.3
* Gatsby CLI version: 2.8.11
* Gatsby version: 2.17.15
* Node Version: v13.6.0
* OS: Ubuntu 18.04

**Comment by styxlab** [comment] 2020-02-21 14:25
As long as you keep your ghost cms docker container up and running, images should be found (and displayed) through `http://localhost:3001/content/images/`. Images are served directly from your ghost cms and only those links are included in your gatsby site.

I'm currently working on a better solution, where all images are included in the gatsby build. This will  allow for image processing in gatsby and will boost page loading and app responsiveness.

**Comment by codevedas** [comment] 2020-04-02 03:50
Any progress to capture all images in the gatsby build. This will allow for image processing in gatsby and will boost page loading and app responsiveness. 

> As long as you keep your ghost cms docker container up and running, images should be found (and displayed) through `http://localhost:3001/content/images/`. Images are served directly from your ghost cms and only those links are included in your gatsby site. So, the idea is that you have a publicly available ghost cms installation and all pictures get served from there.
> 
> I'm currently working on a better solution, where all images are included in the gatsby build. This will allow for image processing in gatsby and will boost page loading and app responsiveness. This feature must be solved upstream at [TryGhost/gatsby-source-ghost#5](https://github.com/TryGhost/gatsby-source-ghost/issues/5).

Any progress to capture all images in the gatsby build. This will allow for image processing in gatsby and will boost page loading and app responsiveness. ?
Found this plugin 
https://www.gatsbyjs.org/packages/gatsby-plugin-remote-images/

**Comment by pmcgrathpoppulo** [comment] 2020-05-18 12:00
I'm interested to know if there are any updates on this, as the issue causes screen tearing on Chrome. 

To reproduce the visual issue using the demo site, open https://gatsby.ghost.org/ and scroll downwards immediately. You should see black "tearing" as the images load.

**Comment by aileen** [comment] 2020-06-29 08:53
Sorry for the late reply. 

> Images are served directly from your ghost cms and only those links are included in your gatsby site. So, the idea is that you have a publicly available ghost cms installation and all pictures get served from there.

The answer @styxlab gave here is 👌 

It's not intended atm to include the images in the build. Going to close this, as it's not an issue.

**Closed by aileen** 2020-06-29 08:53 UTC

**Comment by tobyglei** [comment] 2020-12-04 07:55
I was expecting the images from posts were all included when I `build`. It turns out it's not the case. Hope to see this is a feature on Ghost + Gatsby so it doesn't reply on the CMS to load content in Live.
