### ISSUE TITLE
GraphQL error on start

### ISSUE THREAD

**Issue by celinenguyen** [TryGhost/gatsby-starter-ghost#28] opened 2019-01-25 01:52 UTC
My issue is fairly similar to https://github.com/TryGhost/gatsby-starter-ghost/issues/17, but I'm using a newer version. Just cloned the repo a few minutes ago (on commit 832f18b768443563a9d903bbab20cf30c3bdbc1b). I ran the following commands:

`gatsby new gatsby-starter-ghost https://github.com/TryGhost/gatsby-starter-ghost.git`
`yarn`
`gatsby develop`

And here's the error I'm receiving:

```
GraphQL Error Unknown field `file` on type `Query`

  file: /Users/Celine/…/gatsby-starter-ghost/src/components/common/Layout.js

   1 | 
   2 |             query GhostSettings {
   3 |                 allGhostSettings {
   4 |                     edges {
   5 |                         node {
   6 |                             ...GhostSettingsFields
   7 |                         }
   8 |                     }
   9 |                 }
> 10 |                 file(relativePath: {eq: "ghost-icon.png"}) {
     |                 ^
  11 |                     childImageSharp {
```

If it helps, I'm on Mac OS X, npm 6.5.0, Gatsby 2.4.8, yarn 1.11.0. Haven't used Gatsby before, so apologies if this is quite basic!

**Comment by AileenCGN** [comment] 2019-03-04 06:20
Hey @celinenguyen 👋 

Sorry for that delay here!

Did you sort this out in the meantime? If not, could you please tell me, if this file `src/images/ghost-icon.png` exists for you? It seems like it doesn't...

**Comment by PhilippCh** [comment] 2019-03-22 16:52
The file exists for me and the error persists. Works on macOS, crashes on Windows.

**Comment by AileenCGN** [comment] 2019-03-25 03:21
This sounds actually as if it's related to the `gastby-plugin-sharp`, not this specific starter then: https://www.gatsbyjs.org/docs/gatsby-on-windows/#gatsby-plugin-sharp-requires-node-x64

Unfortunately, I have no way to test this on Windows. I'd recommend that you follow the setup steps as mentioned on the Gatsby page for Windows installs.

I'll close this issue, as it doesn't seem to be caused by the starter. We can reopen it, if it turns out that it's a bug indeed.

**Closed by AileenCGN** 2019-03-25 03:21 UTC
Labels: needs info

**Comment by PhilippCh** [comment] 2019-04-04 20:41
As of today the issue still persists, I've checked that I've installed node x64. Is there anything I can provide to aid in debugging?

**Comment by AileenCGN** [comment] 2019-04-05 00:35
There's not so much I can do here, as this is an issue with Windows and image-sharp. You could remove the dependency `gatsby-plugin-sharp` and only rely on the logo as set in your Ghost publication. The only place where it's used, is the `Layout` component [here](https://github.com/TryGhost/gatsby-starter-ghost/blob/30c5d48d6a01c3b6c2effa34d34188a0964daaa7/src/components/common/Layout.js#L44-L45) and [here](https://github.com/TryGhost/gatsby-starter-ghost/blob/30c5d48d6a01c3b6c2effa34d34188a0964daaa7/src/components/common/Layout.js#L119-L126)
