### ISSUE TITLE
Unable to enabe Google Analytics

### ISSUE THREAD

**Issue by danksky** [TryGhost/gatsby-starter-ghost#308] opened 2020-11-24 05:56 UTC
I've followed both of the following tutorials:

https://www.jamify.org/2020/07/15/running-a-professional-blog-for-free
https://ghost.org/integrations/google/

However, whatever I add to the Header through code injection doesn't get included in the actual build even after running 

```bash
yarn clean
yarn build
gatsby serve
```

**Comment by yoshinator** [comment] 2021-01-03 21:55
I think that is a wider issue and not something particular to this template. I recommend you follow this issue to get updates on when it will be fixed. https://github.com/TryGhost/gatsby-starter-ghost/issues/22

For now what I ended up doing which might or might not be the right thing to do is to add a new script tag inside of the helmet component and put my analytics snippet there. 

`
...    
const analytics = `window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());

                    gtag('config', 'YOURTAG');`;

    return (
        <>
            <Helmet>
                <html lang={site.lang} />
                    <script async src="https://www.googletagmanager.com/gtag/js?id=G-0FKD4DP8GY"></script>
                    <script>
                     {analytics}
                    </script>
                <style type="text/css">{`${site.codeinjection_styles}`}</style>
                <body className={bodyClass} />
            </Helmet>
            ...
            `

**Comment by aileen** [comment] 2021-01-21 20:21
Closing as it's tracked w/ #22 and the cause of the issue.

**Closed by aileen** 2021-01-21 20:21 UTC
