### ISSUE TITLE
TypeError: page is null when its empty

### ISSUE THREAD

**Issue by btmarouane** [TryGhost/gatsby-starter-ghost#281] opened 2020-10-17 23:08 UTC
## Issue
TypeError: page is null
Page
src/templates/page.js:27

  24 |     type="website"
  25 | />
  26 | <Helmet>
> 27 |     <style type="text/css">{`${page.codeinjection_styles}`}</style>
  28 | </Helmet>
  29 | <Layout>
  30 |     <div className="container">

### To Reproduce
Create an empty page and build the app
the graphql query in page.js throws "Cannot return null for non-nullable field GhostPage.html." 
query ($slug: String!) {
  ghostPage(slug: {eq: $slug}) {
    ...GhostPageFields
  }
}

### Technical details:

* Ghost Version: 1.15.0
* Gatsby Version: 2.24.78
* Node Version: 12.10
* OS: Mac

**Comment by aileen** [comment] 2020-10-18 22:20
duplicate of https://github.com/TryGhost/gatsby-starter-ghost/issues/262

**Closed by aileen** 2020-10-18 22:20 UTC
